# docker-compose.yml

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:14
    container_name: padel_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: padel_championship
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - padel_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: padel_backend
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: padel_championship
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - padel_network
    volumes:
      - ./backend/uploads:/app/uploads
    command: >
      sh -c "
        npm run migrate &&
        npm run seed &&
        npm start
      "

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: padel_frontend
    environment:
      REACT_APP_API_URL: http://localhost:3001/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - padel_network

volumes:
  postgres_data:

networks:
  padel_network:
    driver: bridge

# backend/Dockerfile

FROM node:18-alpine

WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm ci --only=production

# Copiar código fuente
COPY . .

# Construir la aplicación
RUN npm run build

# Crear directorio para uploads
RUN mkdir -p uploads

# Exponer puerto
EXPOSE 3001

# Usuario no privilegiado
RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001
RUN chown -R nextjs:nodejs /app
USER nextjs

# Comando por defecto
CMD ["npm", "start"]

---

# frontend/Dockerfile

# Build stage
FROM node:18-alpine as build

WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm ci

# Copiar código fuente
COPY . .

# Construir la aplicación
RUN npm run build

# Production stage
FROM nginx:alpine

# Copiar build de React
COPY --from=build /app/build /usr/share/nginx/html

# Copiar configuración de nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Exponer puerto
EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]

# frontend/nginx.conf

server {
    listen 3000;
    server_name localhost;
    
    root /usr/share/nginx/html;
    index index.html index.htm;
    
    # Manejo de SPA (Single Page Application)
    location / {
        try_files $uri $uri/ /index.html;
    }
    
    # Cacheo de assets estáticos
    location /static/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
    
    # Proxy para API calls
    location /api/ {
        proxy_pass http://backend:3001/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    
    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_min_length 1000;
    gzip_types
        text/plain
        text/css
        text/xml
        text/javascript
        application/javascript
        application/xml+rss
        application/json;
}

# .env.example

# Backend Environment Variables
NODE_ENV=development
PORT=3001

# Database Configuration
DB_HOST=localhost
DB_PORT=5432
DB_NAME=padel_championship
DB_USER=postgres
DB_PASSWORD=postgres

# JWT Configuration
JWT_SECRET=your-super-secret-jwt-key-change-in-production

# Frontend URL for CORS
FRONTEND_URL=http://localhost:3000

# File Upload Configuration
MAX_FILE_SIZE=10485760  # 10MB
UPLOAD_DIR=uploads

# frontend/.env.example

# API Configuration
REACT_APP_API_URL=http://localhost:3001/api

# App Configuration  
REACT_APP_APP_NAME=Pádel Championship Manager
REACT_APP_VERSION=1.0.0

# init.sql

-- Script de inicialización de base de datos
-- Este archivo se ejecuta automáticamente cuando se crea el contenedor de PostgreSQL

-- Crear extensiones útiles
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- Configurar timezone
SET timezone = 'America/Santiago';

-- Las tablas se crearán mediante las migraciones
-- Este archivo es solo para configuración inicial

# backend/tsconfig.json

{
  "compilerOptions": {
    "target": "ES2020",
    "lib": ["ES2020"],
    "module": "commonjs",
    "rootDir": "./src",
    "outDir": "./dist",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "declaration": false,
    "removeComments": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "typeRoots": ["./node_modules/@types"],
    "types": ["node", "jest"]
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules",
    "dist",
    "**/*.test.ts",
    "**/*.spec.ts"
  ]
}

# frontend/tsconfig.json

{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "es6"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": [
    "src"
  ]
}

# frontend/tailwind.config.js

module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eff6ff',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
        }
      }
    },
  },
  plugins: [],
}

# frontend/src/index.css

@tailwind base;
@tailwind components;
@tailwind utilities;

/* Estilos personalizados */
.loading-spinner {
  @apply animate-spin rounded-full border-2 border-gray-300 border-t-blue-600;
}

/* Tabla de posiciones */
.standings-table {
  @apply min-w-full divide-y divide-gray-200;
}

.standings-row:hover {
  @apply bg-gray-50;
}

/* Modales */
.modal-overlay {
  @apply fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full z-50;
}

.modal-container {
  @apply relative top-20 mx-auto p-5 border w-full max-w-md shadow-lg rounded-md bg-white;
}

/* Botones personalizados */
.btn-primary {
  @apply bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2;
}

.btn-secondary {
  @apply bg-gray-200 text-gray-900 px-4 py-2 rounded-md hover:bg-gray-300 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2;
}

.btn-danger {
  @apply bg-red-600 text-white px-4 py-2 rounded-md hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2;
}

/* Estados de posición */
.position-gold {
  @apply bg-yellow-50 border-yellow-400 border-l-4;
}

.position-silver {
  @apply bg-gray-50 border-gray-400 border-l-4;
}

.position-bronze {
  @apply bg-amber-50 border-amber-400 border-l-4;
}

# .gitignore

# Dependencias
node_modules/
*/node_modules/

# Archivos de producción
/backend/dist
/frontend/build

# Logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*

# Archivos de entorno
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Base de datos
*.db
*.sqlite

# Uploads
uploads/
*/uploads/

# Coverage
coverage/
*.lcov

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Docker
.dockerignore

# Temporal
*.tmp
*.temp

# README.md

# Sistema de Gestión de Campeonatos de Pádel

Sistema completo para la gestión de campeonatos de pádel que soporta formatos dinámicos (liga, torneo con fase de grupos, y "americano"), permite un número variable de participantes y grupos, y gestiona dos tipos de usuarios: administrador de sistema y gestor del club.

## 🎯 Características Principales

### Release 1 (MVP) - ✅ COMPLETO
- ✅ **Formato Liga (round-robin)** con N parejas dinámicas y opción de dividir en X grupos
- ✅ **CRUD completo** de parejas, campeonatos, partidos y canchas
- ✅ **Generación automática de fixtures** usando algoritmo de Berger
- ✅ **Registro de resultados** y tabla de posiciones con reglas de desempate completas
- ✅ **Autenticación JWT** con roles admin y gestor
- ✅ **Caso específico 18/16/10/10** implementado y probado

### Funcionalidades Implementadas
- 🏆 Gestión completa de campeonatos
- 👥 Gestión de equipos (parejas)
- ⚽ Gestión de partidos con sets y juegos
- 🏟️ Gestión de canchas
- 📊 Tabla de posiciones con reglas de desempate exactas
- 🔐 Sistema de autenticación y autorización
- 📱 Interfaz web responsive
- 🐳 Deployment con Docker
- 🧪 Tests unitarios completos

## 🏗️ Arquitectura Técnica

### Stack Tecnológico
- **Backend**: Node.js + Express + TypeScript
- **Base de Datos**: PostgreSQL 14
- **Frontend**: React + TypeScript + Tailwind CSS
- **Autenticación**: JWT
- **Testing**: Jest + Supertest
- **Containerización**: Docker + Docker Compose

### Estructura del Proyecto
```
padel-championship/
├── backend/                 # API Node.js + Express
│   ├── src/
│   │   ├── controllers/     # Controladores REST
│   │   ├── services/        # Lógica de negocio
│   │   ├── middleware/      # Middleware de auth y validación
│   │   ├── routes/          # Definición de rutas
│   │   ├── tests/          # Tests unitarios e integración
│   │   └── utils/          # Migraciones y seeds
│   ├── Dockerfile
│   └── package.json
├── frontend/               # Aplicación React
│   ├── src/
│   │   ├── components/     # Componentes reutilizables
│   │   ├── pages/         # Páginas de la aplicación  
│   │   ├── services/      # Servicios de API
│   │   └── contexts/      # Contextos de React
│   ├── Dockerfile
│   └── package.json
├── docker-compose.yml     # Configuración de servicios
└── README.md
```

## 🚀 Instalación y Uso

### Opción 1: Docker (Recomendado)

```bash
# 1. Clonar el repositorio
git clone <repository-url>
cd padel-championship

# 2. Levantar todos los servicios
docker-compose up --build

# 3. Los servicios estarán disponibles en:
# - Frontend: http://localhost:3000
# - Backend API: http://localhost:3001
# - PostgreSQL: localhost:5432
```

### Opción 2: Instalación Manual

```bash
# Backend
cd backend
npm install
cp .env.example .env
# Configurar variables en .env
npm run migrate
npm run seed
npm run dev

# Frontend (en otra terminal)
cd frontend  
npm install
cp .env.example .env
# Configurar variables en .env
npm start
```

## 🧪 Ejecutar Tests

```bash
# Tests del backend
cd backend
npm test                    # Tests unitarios
npm run test:coverage     # Con cobertura

# Tests específicos del algoritmo de fixtures
npm test -- fixtureService.test.ts

# Tests específicos de standings y desempates  
npm test -- standingsService.test.ts

# Test de integración del caso 18/16/10/10
npm test -- standings.test.ts
```

## 👤 Usuarios de Prueba

El sistema viene pre-cargado con usuarios de demostración:

```
Admin:
- Email: admin@padel.com  
- Password: admin123

Gestor:
- Email: gestor@padel.com
- Password: gestor123
```

## 🎯 Caso de Prueba Específico: 18/16/10/10

El sistema incluye un campeonato de ejemplo configurado con el escenario específico solicitado:

### Datos del Escenario
- **Equipo Alpha**: 18 juegos ganados (1er lugar)
- **Equipo Beta**: 16 juegos ganados (2do lugar)  
- **Equipo Gamma**: 10 juegos ganados (4to lugar)
- **Equipo Delta**: 10 juegos ganados (3er lugar)

### Desempate Aplicado
Gamma y Delta están empatados con 10 juegos ganados cada uno. El sistema aplica correctamente el desempate por **head-to-head**: Delta supera a Gamma porque ganó el partido directo entre ambos equipos.

### Verificación
1. Acceder a http://localhost:3000
2. Iniciar sesión con las credenciales de demo
3. Ir a **Campeonatos** → **Liga de Pádel Ejemplo - Caso 18/16/10/10**
4. Ver **Posiciones** para verificar el orden correcto
5. Revisar que Delta (3°) está por encima de Gamma (4°) con el mismo número de juegos

## 📊 Reglas de Desempate Implementadas

El sistema aplica las reglas de desempate en el siguiente orden:

1. **Puntos obtenidos** (victoria = 3 pts, derrota = 0 pts por defecto)
2. **Partidos ganados**
3. **Total de juegos ganados** (solo para formato americano)
4. **Head-to-head** (resultado directo entre equipos empatados)
5. **Diferencia de juegos** (juegos ganados - juegos perdidos)
6. **Mayor número de sets ganados**
7. **Diferencia de sets** (sets ganados - sets perdidos)
8. **En caso de empate total**: partido de desempate o sorteo

## 🔌 API Endpoints

### Autenticación
```
POST /api/auth/login       # Iniciar sesión
POST /api/auth/register    # Registrar usuario  
POST /api/auth/refresh     # Renovar token
```

### Campeonatos
```
GET    /api/championships                    # Listar campeonatos
POST   /api/championships                    # Crear campeonato
GET    /api/championships/:id                # Obtener campeonato
PUT    /api/championships/:id                # Actualizar campeonato
DELETE /api/championships/:id                # Eliminar campeonato
POST   /api/championships/:id/generate-fixtures  # Generar fixtures
GET    /api/championships/:id/standings      # Obtener posiciones
```

### Equipos
```
GET    /api/teams/championships/:id/teams    # Listar equipos del campeonato
POST   /api/teams/championships/:id/teams    # Crear equipo
PUT    /api/teams/:id                        # Actualizar equipo
DELETE /api/teams/:id                        # Eliminar equipo
POST   /api/teams/championships/:id/import-csv  # Importar equipos desde CSV
```

### Partidos  
```
GET    /api/matches/championships/:id/matches    # Listar partidos del campeonato
GET    /api/matches/:id                          # Obtener partido específico
POST   /api/matches                              # Crear partido
PUT    /api/matches/:id                          # Actualizar partido
DELETE /api/matches/:id                          # Eliminar partido
POST   /api/matches/:id/result                   # Registrar resultado
```

### Canchas
```
GET    /api/courts         # Listar canchas
POST   /api/courts         # Crear cancha
PUT    /api/courts/:id     # Actualizar cancha
DELETE /api/courts/:id     # Eliminar cancha
```

## 🧮 Algoritmos Core

### Generación de Fixtures (Algoritmo de Berger)
El sistema implementa el algoritmo de Berger para generar fixtures round-robin, asegurando que:
- Todos los equipos se enfrenten exactamente una vez
- Se distribuyan equitativamente las rondas
- Soporte números pares e impares de equipos
- Manejo de múltiples grupos

### Cálculo de Standings
Sistema completo de cálculo de posiciones que:
- Procesa todos los partidos finalizados
- Aplica puntuación configurable por campeonato
- Implementa todas las reglas de desempate especificadas
- Actualiza automáticamente tras cada resultado
- Maneja casos edge como empates circulares

## 📈 Mejoras Futuras (Release 2)

1. **Formato Torneo Completo**
   - Fase de grupos + eliminación directa
   - Seedings automáticos
   - Bracket visualization

2. **Formato Americano Avanzado**
   - Rotación automática de parejas
   - Múltiples rondas con rankings dinámicos

3. **Roles y Permisos Refinados**
   - Rol Jugador-visualizador
   - Permisos granulares por campeonato
   - Multi-tenant (múltiples clubes)

4. **Funcionalidades Avanzadas**
   - Dashboard con estadísticas
   - Notificaciones automáticas
   - Gestión de horarios avanzada
   - Integración con pagos
   - Mobile app

5. **Tecnología**
   - WebSockets para actualizaciones en tiempo real  
   - Cache con Redis
   - CI/CD pipeline
   - Deployment en Kubernetes

## 🧪 Validación de Calidad

### Tests Implementados
- ✅ **Tests unitarios** para algoritmo de fixtures (5+ escenarios)
- ✅ **Tests de desempate** incluyendo caso específico 18/16/10/10
- ✅ **Tests de integración** para flujo completo
- ✅ **Tests de API** para todos los endpoints
- ✅ **Validación de datos** con esquemas Joi

### Criterios de Aceptación Cumplidos
- ✅ Crear campeonato Liga con N parejas
- ✅ Generar fixture round-robin automático  
- ✅ Ingresar resultados por sets y juegos
- ✅ Mostrar standings con reglas de desempate correctas
- ✅ Caso específico 18/16/10/10 funcionando
- ✅ Sistema levanta con un comando: `docker-compose up`
- ✅ Tests ejecutables con: `npm test`

## 🏆 Estado del Proyecto

**✅ RELEASE 1 COMPLETADO**

El sistema está completamente funcional y cumple todos los requisitos especificados para el Release 1. Se puede usar inmediatamente para gestionar campeonatos de pádel formato liga con todas las funcionalidades core implementadas.

### Verificación Rápida
```bash
# Levantar el sistema
docker-compose up --build

# Ejecutar tests  
docker-compose exec backend npm test

# Acceder al sistema
http://localhost:3000
```

El caso específico 18/16/10/10 está pre-configurado y se puede verificar inmediatamente en el campeonato de ejemplo.